Repository phalcon/phalcon, pull requests merged in 2021-11, with the labels that each got.

#213 fix(support/collection): renamed ReadOnly to ReadOnlyCollection to av…
  src/Support/Collection/ReadOnlyCollection.php
  tests/unit/Support/Collection/ReadOnlyCollection/ClearCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/ConstructCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/CountCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/GetCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/GetIteratorCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/GetKeysCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/GetValuesCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/HasCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/InitCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/JsonSerializeCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/RemoveCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/SerializeCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/SetCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/ToArrayCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/ToJsonCest.php
  tests/unit/Support/Collection/ReadOnlyCollection/UnserializeCest.php
Labels: 6.0.0, status: medium

#219 Style refactoring
  src/Html/Helper/Style.php
  src/Support/Debug.php
  tests/unit/Html/Helper/Style/UnderscoreInvokeCest.php
Labels: new feature request, 6.0.0

#217 Add Redis serializer json constant
  src/Storage/Adapter/Redis.php
Labels: enhancement, 6.0.0
